# Generated by Django 3.2 on 2022-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220219_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_comments',
            name='comment',
            field=models.TextField(max_length=600),
        ),
    ]
