# Generated by Django 3.2 on 2022-02-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='raised',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
